In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('csic_database.csv')
df.head()

,Unnamed: 0,Method,User-Agent,Pragma,Cache-Control,Accept,Accept-encoding,Accept-charset,language,host,cookie,content-type,connection,lenght,content,classification,URL
0,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=1F767F17239C9B670A39E9B10C3825F4,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/index.jsp HTTP/1.1
1,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=81761ACA043B0E6014CA42A4BCD06AB5,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/anadir.j...
2,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=933185092E0B668B90676E0A2B0767AF,application/x-www-form-urlencoded,Connection: close,Content-Length: 68,id=3&nombre=Vino+Rioja&precio=100&cantidad=55&...,0,http://localhost:8080/tienda1/publico/anadir.j...
3,Normal,GET,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=8FA18BA82C5336D03D3A8AFA3E68CBB0,NaN,close,NaN,NaN,0,http://localhost:8080/tienda1/publico/autentic...
4,Normal,POST,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,localhost:8080,JSESSIONID=7104E6C68A6BCF1423DAE990CE49FEE2,application/x-www-form-urlencoded,Connection: close,Content-Length: 63,modo=entrar&login=choong&pwd=d1se3ci%F3n&remem...,0,http://localhost:8080/tienda1/publico/autentic...

In [3]:
df['URL'].tail()

61060    http://localhost:8080/tienda1/miembros/editar....
61061    http://localhost:8080/tienda1/miembros/editar....
61062    http://localhost:8080/tienda1/miembros/editar....
61063    http://localhost:8080/tienda1/imagenes/3.gif/ ...
61064    http://localhost:8080/tienda1/imagenes/nuestra...
Name: URL, dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61065 entries, 0 to 61064
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       61065 non-null  object
 1   Method           61065 non-null  object
 2   User-Agent       61065 non-null  object
 3   Pragma           61065 non-null  object
 4   Cache-Control    61065 non-null  object
 5   Accept           60668 non-null  object
 6   Accept-encoding  61065 non-null  object
 7   Accept-charset   61065 non-null  object
 8   language         61065 non-null  object
 9   host             61065 non-null  object
 10  cookie           61065 non-null  object
 11  content-type     17977 non-null  object
 12  connection       61065 non-null  object
 13  lenght           17977 non-null  object
 14  content          17977 non-null  object
 15  classification   61065 non-null  int64
 16  URL              61065 non-null  object
dtypes: int64(1), object(16)
memory usage: 7.9+ MB

In [5]:
df["INDEX"] = df.index

In [6]:
df['INDEX']

0            0
1            1
2            2
3            3
4            4
         ...
61060    61060
61061    61061
61062    61062
61063    61063
61064    61064
Name: INDEX, Length: 61065, dtype: int64

In [7]:
# Séparer les lignes normales et malveillantes
normal_df = df[df['classification'] == 0].sample(n=5000, random_state=42)
attack_df = df[df['classification'] == 1].sample(n=5000, random_state=42)

# Fusionner et supprimer la colonne classification
test_df = pd.concat([normal_df, attack_df]).drop(columns=["classification"])


# Sauvegarder le jeu de test sans labels
test_df.to_csv("test_dataset_10000.csv", index=False)

In [8]:
# Pour pouvoir évaluer ton modèle plus tard
labels_df = pd.concat([normal_df, attack_df])[['classification']]
labels_df.to_csv("test_labels_10000.csv", index=False)

In [9]:
df_test_data=pd.read_csv('test_dataset_10000.csv')
df_test_label=pd.read_csv('test_labels_10000.csv')

In [10]:
df_test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       10000 non-null  object
 1   Method           10000 non-null  object
 2   User-Agent       10000 non-null  object
 3   Pragma           10000 non-null  object
 4   Cache-Control    10000 non-null  object
 5   Accept           9918 non-null   object
 6   Accept-encoding  10000 non-null  object
 7   Accept-charset   10000 non-null  object
 8   language         10000 non-null  object
 9   host             10000 non-null  object
 10  cookie           10000 non-null  object
 11  content-type     3166 non-null   object
 12  connection       10000 non-null  object
 13  lenght           3166 non-null   object
 14  content          3166 non-null   object
 15  URL              10000 non-null  object
 16  INDEX            10000 non-null  int64
dtypes: int64(1), object(16)
memory usage: 1.3+ MB

In [11]:
df_test_label.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   classification  10000 non-null  int64
dtypes: int64(1)
memory usage: 78.2 KB

In [12]:
df_test_label

      classification
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
9995               1
9996               1
9997               1
9998               1
9999               1

[10000 rows x 1 columns]

In [13]:
df_test_data['INDEX']

0       16461
1       23579
2       23640
3       25635
4        8840
        ...
9995    40863
9996    40751
9997    41071
9998    53123
9999    50410
Name: INDEX, Length: 10000, dtype: int64

In [14]:
# 1. Récupérer les INDEX du jeu de test
test_indices = df_test_data["INDEX"]

# 2. Supprimer ces lignes du DataFrame d'origine
df_train = df[~df["INDEX"].isin(test_indices)]
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51065 entries, 0 to 61064
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       51065 non-null  object
 1   Method           51065 non-null  object
 2   User-Agent       51065 non-null  object
 3   Pragma           51065 non-null  object
 4   Cache-Control    51065 non-null  object
 5   Accept           50750 non-null  object
 6   Accept-encoding  51065 non-null  object
 7   Accept-charset   51065 non-null  object
 8   language         51065 non-null  object
 9   host             51065 non-null  object
 10  cookie           51065 non-null  object
 11  content-type     14811 non-null  object
 12  connection       51065 non-null  object
 13  lenght           14811 non-null  object
 14  content          14811 non-null  object
 15  classification   51065 non-null  int64
 16  URL              51065 non-null  object
 17  INDEX            51065 non-null  int64
dtypes: int64(2), object(16)
memory usage: 7.4+ MB

In [15]:
df_train.to_csv("csic_train.csv", index=False)

In [16]:
import os
os.environ["SPARK_HOME"] = "C:/Users/ViVo/Downloads/spark-3.4.4-bin-hadoop3/spark-3.4.4-bin-hadoop3"

import findspark
findspark.init()

In [17]:

from pyspark.sql import SparkSession
from pyspark.sql.functions import col
from pyspark.ml.feature import Tokenizer, HashingTF, StringIndexer, VectorAssembler
from pyspark.ml.classification import LogisticRegression
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

In [18]:
# 1. Create Spark session
spark = SparkSession.builder \
    .appName("CSIC MLlib Training") \
    .config("spark.driver.memory", "4g") \
    .getOrCreate()

In [19]:
# 2. Load CSV dataset into Spark DataFrame
df_ML = spark.read.csv("csic_train.csv", header=True, inferSchema=True)

In [ ]:
# 3. Select and clean useful columns
selected_cols = ["Method", "URL", "User-Agent", "content", "classification"]
df_ML = df_ML.select(*selected_cols).na.fill({"content": ""})

# ⚠️ NEW: Sample 5000 normal + 5000 anomalies
#normal_df = df_ML.filter(col("classification") == 0).orderBy(col("Method")).limit(5000)
#anomaly_df = df_ML.filter(col("classification") == 1).orderBy(col("Method"), ascending=False).limit(5000)
#df_sample = normal_df.union(anomaly_df)

# 4. Encode Method column
method_indexer = StringIndexer(inputCol="Method", outputCol="Method_Indexed")

# 5. Tokenize and vectorize text columns
url_tokenizer = Tokenizer(inputCol="URL", outputCol="URL_Tokens")
url_tf = HashingTF(inputCol="URL_Tokens", outputCol="URL_Features")

agent_tokenizer = Tokenizer(inputCol="User-Agent", outputCol="Agent_Tokens")
agent_tf = HashingTF(inputCol="Agent_Tokens", outputCol="Agent_Features")

content_tokenizer = Tokenizer(inputCol="content", outputCol="Content_Tokens")
content_tf = HashingTF(inputCol="Content_Tokens", outputCol="Content_Features")

In [21]:
# 6. Assemble features
assembler = VectorAssembler(
    inputCols=["Method_Indexed", "URL_Features", "Agent_Features", "Content_Features"],
    outputCol="features"
)

In [22]:
from pyspark.ml.classification import LinearSVC

# 7. Define model (SVM)
lr = LogisticRegression(labelCol="classification", featuresCol="features")

In [23]:
# 8. Build pipeline
pipeline = Pipeline(stages=[
    method_indexer,
    url_tokenizer, url_tf,
    agent_tokenizer, agent_tf,
    content_tokenizer, content_tf,
    assembler,
    lr
])

In [24]:
# 9. Fit the model
model = pipeline.fit(df_ML)

# 10. Predict on training data
predictions = model.transform(df_ML)

# 11. Evaluate model
evaluator = MulticlassClassificationEvaluator(
    labelCol="classification",
    predictionCol="prediction",
    metricName="f1"
)

f1_score = evaluator.evaluate(predictions)
print(f"✅ F1-score on training data: {f1_score:.4f}")

✅ F1-score on training data: 0.9965

In [26]:
# 12. Load test dataset (without labels)
df_test = spark.read.csv("test_dataset_10000.csv", header=True, inferSchema=True).na.fill({"content": ""})

# 13. Predict on test dataset
test_predictions = model.transform(df_test)
test_predictions.select("Method", "URL", "prediction").show(10)

+------+--------------------+----------+
|Method|                 URL|prediction|
+------+--------------------+----------+
|  POST|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
+------+--------------------+----------+
only showing top 10 rows

In [33]:
df_test = df_test.drop(df_test.columns[0])

In [34]:
df_test.select(df_test.columns[0]).show(10)

+------+
|Method|
+------+
|  POST|
|   GET|
|   GET|
|   GET|
|   GET|
|   GET|
|   GET|
|   GET|
|   GET|
|   GET|
+------+
only showing top 10 rows

In [35]:
# 13. Predict on test dataset
test_predictions = model.transform(df_test)
test_predictions.select("Method", "URL", "prediction").show(10)

+------+--------------------+----------+
|Method|                 URL|prediction|
+------+--------------------+----------+
|  POST|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
|   GET|http://localhost:...|       0.0|
+------+--------------------+----------+
only showing top 10 rows

In [36]:
from pyspark.sql.functions import col, monotonically_increasing_id

# 14. Evaluate model on test set (with true labels)
df_labels = spark.read.csv("test_labels_10000.csv", header=True, inferSchema=True)

# Add an index to both DataFrames to join them
predictions_indexed = test_predictions.withColumn("index", monotonically_increasing_id())
labels_indexed = df_labels.withColumn("index", monotonically_increasing_id())

df_test_labeled = predictions_indexed.join(labels_indexed, on="index").drop("index")

# Evaluate
test_evaluator = MulticlassClassificationEvaluator(
    labelCol="classification",
    predictionCol="prediction",
    metricName="f1"
)

f1_score_test = test_evaluator.evaluate(df_test_labeled)
print(f"✅ F1-score on test data: {f1_score_test:.4f}")

✅ F1-score on test data: 0.8054

In [37]:
df_test_labeled = predictions_indexed.join(labels_indexed, on="index").drop("index")

In [ ]:
df_test_labeled.show(10)

+------+--------------------+--------+-------------+--------------------+--------------------+--------------------+--------+--------------+--------------------+--------------------+-----------------+------------------+--------------------+--------------------+--------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------+----------+--------------+
|Method|          User-Agent|  Pragma|Cache-Control|              Accept|     Accept-encoding|      Accept-charset|language|          host|              cookie|        content-type|       connection|            lenght|             content|                 URL|Method_Indexed|          URL_Tokens|        URL_Features|        Agent_Tokens|      Agent_Features|      Content_Tokens|    Content_Features|            features|       rawPrediction|probability|prediction|classification|
+------+--------------------+--------+-------------+--------------------+--------------------+--------------------+--------+--------------+--------------------+--------------------+-----------------+------------------+--------------------+--------------------+--------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------+----------+--------------+
|  POST|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=35D2A6...|application/x-www...|Connection: close|Content-Length: 33|errorMsg=Credenci...|http://localhost:...|           1.0|[http://localhost...|(262144,[98390,15...|[mozilla/5.0, (co...|(262144,[36314,57...|[errormsg=credenc...|(262144,[193866],...|(786433,[0,98391,...|[43.2348780862151...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=39D951...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[16644,98...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[16645,98...|[132.134155600287...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=89882E...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,25...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,25...|[132.139439337392...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=400CCA...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,18...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,18...|[49.0587857212649...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=BD9163...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,13...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,13...|[132.136231691955...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=E13AB4...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,13...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,13...|[132.136231691955...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=135095...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,10...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,10...|[132.138118668727...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=56C518...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,11...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,11...|[132.136231691955...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=A3F824...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,23...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,23...|[132.136986526026...|  [1.0,0.0]|       0.0|             0|
|   GET|Mozilla/5.0 (comp...|no-cache|     no-cache|text/xml,applicat...|x-gzip, x-deflate...|utf-8, utf-8;q=0....|      en|localhost:8080|JSESSIONID=A15CE9...|                null|            close|              null|                    |http://localhost:...|           0.0|[http://localhost...|(262144,[98390,18...|[mozilla/5.0, (co...|(262144,[36314,57...|                  []|(262144,[249180],...|(786433,[98391,18...|[132.142457343041...|  [1.0,0.0]|       0.0|             0|
+------+--------------------+--------+-------------+--------------------+--------------------+--------------------+--------+--------------+--------------------+--------------------+-----------------+------------------+--------------------+--------------------+--------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------+----------+--------------+
only showing top 10 rows

In [40]:
correct_labeled = df_test_labeled.filter(col("prediction") == col("classification")).count()
print(correct_labeled)
print(f"✅ Prédictions correctes (df_test_labeled) : {correct_labeled} / {df_test_labeled.count()}")

6888
✅ Prédictions correctes (df_test_labeled) : 6888 / 8534